# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(verbose_name='Title')),
                ('topic', models.CharField(max_length=256, null=True, verbose_name='Topic')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Is closed?')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Started by')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
                'ordering': ['create_date'],
            },
            managers=[
                ('admin_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Text')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Channel', verbose_name='Channel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['create_date'],
            },
        ),
    ]
