# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20160309_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='slug',
        ),
    ]
